version: "3.9"

services:
  sample_container:
    build:
      context: .
    container_name: local_bash
    # Added to test if environment variables are accessible
    env_file:
      - ./base/.envs/.local/.sample
    volumes:
      - ./base:/base
    command: compose/local-env/test.sh
    working_dir: /base

  docs:
    container_name: local_docs
    platform: linux/x86_64
    build:
      context: .
    volumes:
      - ./base:/base
    ports:
      - "9000:9000"
    command: compose/local-env/sphinxdocs/startdocs.sh
    working_dir: /base
